CREATE TABLE Brand (
    BrandId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BrandName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Category (
    CategoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Drink (
    DrinkId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BrandId INT,
    AlcoholContent DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (BrandId) REFERENCES Brand(BrandId) ON DELETE SET NULL
);

CREATE TABLE DrinkCategory (
    DrinkId INT,
    CategoryId INT,
    PRIMARY KEY (DrinkId, CategoryId),
    FOREIGN KEY (DrinkId) REFERENCES Drink(DrinkId) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId) ON DELETE CASCADE
);

CREATE TABLE User (
    UserId INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE Vote (
    VoteId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserId INT,
    DrinkId INT,
    VoteTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DrinkId) REFERENCES Drink(DrinkId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE
);

CREATE TABLE DrinkOfTheDay (
    DrinkId INT PRIMARY KEY,
    FOREIGN KEY (DrinkId) REFERENCES Drink(DrinkId),
    DrinkTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserDrink (
    UserId INT,
    DrinkId INT,
    FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
    FOREIGN KEY (DrinkId) REFERENCES Drink(DrinkId) ON DELETE CASCADE
);

INSERT INTO Brand (BrandName) VALUES ("Ursugi");
INSERT INTO Brand (BrandName) VALUES ("Bergenbir");
SELECT * FROM Brand;
