CREATE TABLE Brand (
	BrandId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BrandName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Category (
	CategoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Drink (
	DrinkId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BrandId INT,
    AlcoholContent DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (BrandId) REFERENCES Brand(BrandId) ON DELETE SET NULL
);

CREATE TABLE DrinkCategory (
	DrinkId INT,
    CategoryId INT,
    PRIMARY KEY (DrinkId, CategoryId),
    FOREIGN KEY (DrinkId) REFERENCES Drink(DrinkId) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId) ON DELETE CASCADE
);

CREATE TABLE Votes (
	VoteId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DrinkId INT,
    VoteTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);